language: python
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create -n tracepyci python=3.7 --yes
  - source activate tracepyci
  - >-
      conda install --yes
      numpy
      scipy
      matplotlib>
      scikit-learn
      pandas
      pytest
      pytest-cov
      coveralls
  - pip install .
script:
  - pytest --cov=tracepy tests/
notifications:
  email: false
